### ISSUE TITLE
Add verbosity levels

### ISSUE THREAD

**Issue by kkuchta** [kkuchta/mitt#1]
I'd like to be able to specify how verbose the output should be.  Something like:

#### Low
Each request takes exactly one line.  You could even pipe this output to another command to construct a simple webserver.

```
PATCH /foo | {"biz": "baz"}
GET /bar |
```

#### Medium
This is just what we have now: compact, but human readable.
```
--- PATCH / ---
{"biz": "baz"}
--- GET /bar ---
```

#### High

Human readable and includes headers.
```
--- PATCH / ----
Body:
  {"biz": "baz"}
Headers:
  Host: localhost:12345
  User-Agent: curl/7.43.0
  Accept: */*
  Content-Length: 14
  Content-Type: application/x-www-form-urlencoded
```
